// Authored by Karter Whitman using Claude Opus 4.8
// ULID minting. Ids are generated by whoever builds the change — the
// renderer needs the id before the write lands, so the store can apply
// optimistically — which is why this lives in the shared package rather
// than behind the database.
import { webcrypto } from "node:crypto";

const CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const TIME_CHARS = 10;
const RANDOM_CHARS = 16;

// The renderer has `crypto` on globalThis; Node needs it named.
const random: Crypto = globalThis.crypto ?? (webcrypto as unknown as Crypto);

function encodeTime(now: number): string {
  let out = "";
  let remaining = now;
  for (let index = TIME_CHARS - 1; index >= 0; index -= 1) {
    out = CROCKFORD[remaining % 32] + out;
    remaining = Math.floor(remaining / 32);
  }
  return out;
}

function encodeRandom(): string {
  const bytes = new Uint8Array(RANDOM_CHARS);
  random.getRandomValues(bytes);
  let out = "";
  for (const byte of bytes) out += CROCKFORD[byte % 32];
  return out;
}

/**
 * A ULID: lexically sortable by creation time, random within a
 * millisecond. Monotonicity inside one millisecond is not guaranteed and
 * is not needed — `created_at` is the ordering the app actually reads.
 */
export function ulid(now = Date.now()): string {
  return encodeTime(now) + encodeRandom();
}

export function itemId(): string {
  return `items:${ulid()}`;
}

export function connectionId(): string {
  return `connections:${ulid()}`;
}

export function slugify(name: string, fallback: string): string {
  const slug = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return slug || fallback;
}

/**
 * `labels:author` — a label's id is its slugified name, so first use of
 * the same word always lands on the same record.
 */
export function labelId(name: string): string {
  return `labels:${slugify(name, "label")}`;
}

/** `schemas:book` — same idea as `labelId`: the name is the identity, so
 * editing a type's fields always lands on the same row it started as. */
export function schemaId(name: string): string {
  return `schemas:${slugify(name, "type")}`;
}

/** `items:type_book` — a type's dedicated Space, the same deterministic
 * way `schemaId` names the type itself: creating the type "book" always
 * looks for (and if absent, lands on) this same row, so ensuring the
 * Space exists is a plain idempotent upsert rather than a search. Shares
 * `schemaId`'s slug, prefixed (with `slugify`'s own separator, not a
 * bare `-` — SurrealDB reads an unescaped hyphen in a bare record id as
 * the start of a new token and silently truncates there, so `type-book`
 * and `type-video` both land on the literal id `type`) to stay out of
 * its own `schemas:` table — a Space is an ordinary item, not a schema. */
export function typeSpaceId(name: string): string {
  return `items:type_${slugify(name, "type")}`;
}
