// Authored by Karter Whitman using Claude Opus 4.8
// The channel names, alone in their own module so the preload can import
// them without dragging the main-process handlers (and everything they
// import) into the renderer's bundle.
export const CHANNELS = {
  deviceSelf: "device:self",
  setsList: "sets:list",
  setsMembers: "sets:members",
  setsDates: "sets:dates",
  itemsGet: "items:get",
  itemsSearch: "items:search",
  dataAttributesList: "data:attributes:list",
  labelsList: "labels:list",
  labelsEnsure: "labels:ensure",
  schemasList: "schemas:list",
  schemasUpsert: "schemas:upsert",
  changesApply: "changes:apply",
  intakePathsToResources: "intake:pathsToResources",
  intakePick: "intake:pick",
  ingestClassify: "ingest:classify",
  ingestParse: "ingest:parse",
  ingestModel: "ingest:model",
  modelsLocationsList: "models:locations:list",
  modelsLocationsAdd: "models:locations:add",
  modelsLocationsRemove: "models:locations:remove",
  modelsScan: "models:scan",
  modelsSetActive: "models:setActive",
  itemClassifierClassify: "itemClassifier:classify",
  classificationSettingsGet: "classification:settings:get",
  classificationSettingsSet: "classification:settings:set",
  resourcesCheckMissing: "resources:checkMissing",
  resourcesLocate: "resources:locate",
  resourcesReseek: "resources:reseek",
  resourcesWatchlistList: "resources:watchlist:list",
  resourcesWatchlistAdd: "resources:watchlist:add",
  resourcesWatchlistUpdate: "resources:watchlist:update",
  resourcesExcludelistList: "resources:excludelist:list",
  resourcesExcludelistAdd: "resources:excludelist:add",
  resourcesExcludelistRemove: "resources:excludelist:remove",
  shellReveal: "shell:reveal",
  shellOpenExternal: "shell:openExternal",
  spotifyCredentialsGet: "spotify:credentials:get",
  spotifyCredentialsSave: "spotify:credentials:save",
  spotifyAlbum: "spotify:album",
} as const;
